#请在启动参数中加入--spring.profiles.active=mysql以激活本配置文件
database: mysql

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/bookstore?useUnicode=true&characterEncoding=utf-8"
    username: root
    password: my-secret-pw
    initialization-mode: always
  liquibase:
#    enabled: false
    change-log: classpath:db/liquibase/changelog.xml